url: http://FPGAwars.github.io
baseurl:

# Site settings
title: FPGAwars
email: fpgawars@gmail.com
description: "Exploring the open side of the FPGAs"


# Team names, titles and social links
people:
- name:
  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: google-plus
      url: #

# Build settings
markdown: kramdown
permalink: pretty
